name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run-tests-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install pytest ruff
    - name: Check quality
      run: |
        ruff check gym_pusht setup.py
    - name: Run tests
      run: |
        python -m pytest -v tests/
